### ISSUE TITLE
Exception when opening a ymn file while editing an existing one

### ISSUE THREAD

**Issue by ericverschoor** [yellicode/core#1] opened 2019-04-25 18:15 UTC
Hello,

I'm following your tutorials and bumped into an error. 
Just to let you know....

steps to reproduce are:
open Yellicode modeler, and create a project and add a class
open the tutorial bookstore.ymn.

now an exception will be thrown.

![image](https://user-images.githubusercontent.com/45706519/56758369-c3d85200-6796-11e9-9e0b-c655b45e25c7.png)

**Comment by mdelaat** [comment] 2019-04-26 14:29
Thanks for reporting this issue. I was able to reproduce it, this seems to be introduced by a combination of Electron and a recent Windows update. You can expect this to fixed in the next patch.

**Comment by mdelaat** [comment] 2019-05-10 07:50
This isssue has been fixed in Yellicode Modeler 0.3.10, the update will be installed automatically upon exit. 

Note that opening .ymn files using drag-drop is currently disabled due to another issue, but double-click in Explorer (or Finder on a Mac) will still work.

**Closed as completed by mdelaat** 2019-05-10 07:50 UTC
